name: Quark
options:
  bundleIdPrefix: com.camoulabs
  deploymentTarget:
    iOS: "26.0"
  projectFormat: xcode15_0
targets:
  Quark:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Quark
        type: group
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: "Quark - Learn STEM"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.education"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        MARKETING_VERSION: "1.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.camoulabs.Quark
        PRODUCT_NAME: "Quark - Learn STEM"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
